python -m pytest argo/argo_utils/tests
python -m pytest argo/correlation_reduction/tests
python -m pytest argo/read_data/tests
python -m pytest argo/rule_application/tests
python -m pytest argo/rule_filtering/tests
python -m pytest argo/rule_generation/tests
python -m pytest argo/rule_optimisation/tests
python -m pytest argo/rule_scoring/tests
python -m pytest argo/rules/tests
python -m pytest argo/simility_apis/tests
python -m pytest argo/simility_requests/tests
python -m pytest argo/system_config_generation/tests